#ifndef LIBS_H
#define LIBS_H

#include <QMainWindow>
#include <QAction>
#include <QApplication>
#include <QBoxLayout>
#include <QDebug>
#include <QColor>
#include <QKeyEvent>
#include <QDesktopWidget>
#include <QDialog>
#include <QEvent>
#include <QHBoxLayout>
#include <QLabel>
#include <QLayout>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QMouseEvent>
#include <QMoveEvent>
#include <QPushButton>
#include <QStatusBar>
#include <QStyle>
#include <QToolBar>
#include <QWidget>
#include <QTextEdit>
#include <QLineEdit>
#include <QFileDialog>
#include <QRect>
#include <QDir>
#include <QIcon>
#include <QFile>
#include <QColor>
#include <QColorDialog>
#include <QScrollArea>
#include <QCommandLinkButton>
#include <QComboBox>
#include <QObject>
#include <QInputDialog>
#include <QSpinBox>
#include <QGroupBox>
#include <memory>
#include <cstring>
#include <fstream>
#include <iostream>
#include <math.h>
#include "QMessageBox"
#include <QTimer>

#endif // LIBS_H
